services:
  redis:
    image: redis:7.4.0-alpine
    volumes:
      - ./data/redis:/data
    restart: always

  proxy:
    depends_on:
      - redis
    build: ./proxy
    volumes:
      - ./proxy:/app
      - /app/node_modules
    environment:
      APP_PORT: ${APP_PORT}
      LOG_LEVEL: ${LOG_LEVEL}
      REQUIRE_AUTH: ${REQUIRE_AUTH}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
    ports:
      - "${APP_PORT}:${APP_PORT}"
    expose:
      - "${APP_PORT}/tcp"
    restart: always
